
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot001_factor")
mget(vector_obj)[[1]]

```

```{r}
#| warning: false
#| echo: false

my_df <- df_table_factor_plot001
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)
```


***



```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot002_factor")
mget(vector_obj)[[1]]
```

```{r}
#| warning: false
#| echo: false
my_df <- df_table_factor_plot002
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot003_factor")
mget(vector_obj)[[1]]
```

```{r}
#| warning: false
#| echo: false
my_df <- df_table_factor_plot003
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

***

```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot004_factor")
mget(vector_obj)[[1]]
```


```{r}
#| warning: false
#| echo: false
my_df <- df_table_factor_plot004
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

***

```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot005_factor")
mget(vector_obj)[[1]]
```


```{r}
#| warning: false
#| echo: false

my_df <- df_table_factor_plot005
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

***

```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot006_factor")
mget(vector_obj)[[1]]
```


```{r}
#| warning: false
#| echo: false

my_df <- df_table_factor_plot006
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

***

```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot007_factor")
mget(vector_obj)[[1]]
```


```{r}
#| warning: false
#| echo: false

my_df <- df_table_factor_plot007
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

***


