

```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot001_residuals")
mget(vector_obj)[[1]]
```


```{r}
#| warning: false
#| echo: false
#| 

vector_obj <- "df_table_residuals_plot001"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot002_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot002"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot003_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot003"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot004_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot004"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)


```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot005_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot005"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)


```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot006_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot006"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot007_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot007"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)
```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot008_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot008"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)
```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot009_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot009"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)
```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot010_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| warning: false
#| echo: false

vector_obj <- "df_table_residuals_plot010"
my_df <- mget(vector_obj)
kable(my_df, format = "html", caption = "") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)
```


***

