

```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot001_residuals")
mget(vector_obj)[[1]]
```


```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot001", caption_text = "")

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot002_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot002", caption_text = "")

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot003_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot003", caption_text = "")

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot004_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot004", caption_text = "")


```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot005_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot005", caption_text = "")


```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot006_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot006", caption_text = "")

```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot007_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot007", caption_text = "")
```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot008_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot008", caption_text = "")
```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot009_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot009", caption_text = "")
```


***


```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot010_residuals")
mget(vector_obj)[[1]]
```



```{r}
#| echo: false
fn_show_table_dynamic(object_name = "df_table_residuals_plot010", caption_text = "")
```


***

