---
title: "Parameterized Penguins Report"
author: 'David Elias Panigo'
format:
  typst:
    toc: true
    number-sections: true
    papersize: a4
knitr: 
    opts_chunk: 
        collapse: false
        comment: ""
        # Puedes mantener dev: "png" si usas librerías de gráficos avanzadas
        # o eliminar las tres líneas siguientes si solo usas ggplot o base R nativo.
        dev: "png" 
        fig-ext: "png"
params:
    file_name: "mtcars"
    file_source: "r_source" 
    var_name_rv: "mpg"
    var_name_factor: "cyl"
    alpha_value: "0.05"
    vector_ordered_levels:
      - "6"
      - "4"
      - "8"
    vector_ordered_colors: 
      - "#FF0000"
      - "#00FF00"
      - "#0000FF"
    current_time: "R_outside"
    the_package: "exp002RShiny"
    tool_used: "General Linnear Model, Fixed Effect, anova 1 way"
    script_used: "R_outside"
---

```{r}
#| echo: false
library(knitr)
library(kableExtra)
source("fns.R")
```

```{r}
#| echo: false
my_dataset <- mtcars
fn_show_table_dynamic(object_name = "my_dataset", caption_text = "")

# kable(my_dataset, format = "pipe", caption = "")
# fn_show_table_pdf_typst(object_name = "my_dataset", caption_text = "")
```

